[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
proof_of_battle = "9MFZtJWMutu1E6VDvKSJiDFEncidaoYvrsffr7U1MxCP"

[programs.localnet]
proof_of_battle = "7xStH3SCRkztTc1SWQtcx9ACvwqaYyUJF35dTbpAZG2S"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
